### ISSUE TITLE
Create the Gender model

### ISSUE THREAD

**Issue by MBJean** [dhmit/gender_analysis_web#4]
# Overview
Much of the functionality of the [`gender_analysis`](https://github.com/dhmit/gender_analysis) project centers around a class called [`Gender`](https://github.com/dhmit/gender_analysis/blob/main/gender_analysis/gender/gender.py). Instances of this class are created in order to encapsulate references to gendered pronouns and thereby streamline our various analysis modules that look for those pronouns in textual content.

This basic concept, that the `Gender` class provides an interface for engaging with textual material, will be a useful tool as we move the whole project into a web application architecture. That said, we should replace some of the conventions of this `Gender` class with more suitable web equivalents.

## Goals
- Port over the `Gender` class into `gender_analysis_web` as a Django model.
- Ultimately, allow a user to create new `Gender` records by inputting relevant metadata into a web interface. To do this, we'll need to create both a user interface and API backend to support this interaction.

**Comment by farooqashar** [comment]
`Gender` Model has been merged into `main`
